---
- hosts: appserver
  gather_facts: yes
#  become_method: sudo
  become: yes
  tasks:
    - name: Update the yum repo
      yum:
        name: '*'
        state: latest


    - name: Install the apache server using httpd
      yum:
        name: 'httpd'
        state: latest


